# Generated by Django 5.1.6 on 2026-03-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='office',
            new_name='offices_off_level_17d766_idx',
            old_name='offices_off_level_ba926f_idx',
        ),
    ]
