# Generated by Django 5.1.6 on 2026-03-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='district',
            new_name='geo_distric_distric_a75e4e_idx',
            old_name='geo_distri_distri_846743_idx',
        ),
        migrations.RenameIndex(
            model_name='district',
            new_name='geo_distric_jurisdi_c1cf7e_idx',
            old_name='geo_distri_jurisdi_3c5cf5_idx',
        ),
        migrations.RenameIndex(
            model_name='jurisdiction',
            new_name='geo_jurisdi_state_b565b1_idx',
            old_name='geo_jurisdi_state_64ab3f_idx',
        ),
        migrations.RenameIndex(
            model_name='jurisdiction',
            new_name='geo_jurisdi_state_c53470_idx',
            old_name='geo_jurisdi_state_1e1a7e_idx',
        ),
    ]
