# Generated by Django 5.1.6 on 2026-03-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='videoembed',
            new_name='media_video_provide_cc3cb8_idx',
            old_name='media_video_provider_f6c1c4_idx',
        ),
        migrations.RenameIndex(
            model_name='videoembed',
            new_name='media_video_is_appr_bdedca_idx',
            old_name='media_video_is_appr_9b0bd1_idx',
        ),
    ]
