# Generated by Django 5.1.6 on 2026-03-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mergereview',
            new_name='ingestion_m_status_4fa6f9_idx',
            old_name='ingestion_me_status__7f7c70_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcerecord',
            new_name='ingestion_s_provide_cf55e3_idx',
            old_name='ingestion_so_provider_57bdb5_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcerecord',
            new_name='ingestion_s_payload_fc9f0e_idx',
            old_name='ingestion_so_payload__a0bd07_idx',
        ),
        migrations.RenameIndex(
            model_name='syncrun',
            new_name='ingestion_s_provide_e5c09e_idx',
            old_name='ingestion_sy_provider_8c2b16_idx',
        ),
        migrations.AlterField(
            model_name='sourcerecord',
            name='provider',
            field=models.CharField(choices=[('ballotready_civicengine', 'BallotReady/CivicEngine'), ('ballotpedia', 'Ballotpedia'), ('openstates', 'OpenStates'), ('openfec', 'OpenFEC'), ('youtube', 'YouTube'), ('democracy_works', 'Democracy Works')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='provider',
            field=models.CharField(choices=[('ballotready_civicengine', 'BallotReady/CivicEngine'), ('ballotpedia', 'Ballotpedia'), ('openstates', 'OpenStates'), ('openfec', 'OpenFEC'), ('youtube', 'YouTube'), ('democracy_works', 'Democracy Works')], db_index=True, max_length=64),
        ),
    ]
