# Generated by Django 5.1.6 on 2026-03-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactmethod',
            new_name='people_cont_person__6d5446_idx',
            old_name='people_cont_person_i_b20c1c_idx',
        ),
        migrations.RenameIndex(
            model_name='externallink',
            new_name='people_exte_person__12eda1_idx',
            old_name='people_exte_person_i_24a4fe_idx',
        ),
        migrations.RenameIndex(
            model_name='sociallink',
            new_name='people_soci_person__655d01_idx',
            old_name='people_soci_person_i_965c54_idx',
        ),
    ]
