# Generated by Django 5.1.6 on 2026-03-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='candidacy',
            new_name='elections_c_party_e7727b_idx',
            old_name='elections_ca_party_s_8a4d25_idx',
        ),
        migrations.RenameIndex(
            model_name='candidacy',
            new_name='elections_c_race_id_7fb2b0_idx',
            old_name='elections_ca_race_s_b3e8dc_idx',
        ),
        migrations.RenameIndex(
            model_name='election',
            new_name='elections_e_date_92717e_idx',
            old_name='elections_el_date_987c93_idx',
        ),
        migrations.RenameIndex(
            model_name='officeholderterm',
            new_name='elections_o_office__52c7d7_idx',
            old_name='elections_of_office__a450db_idx',
        ),
        migrations.RenameIndex(
            model_name='officeholderterm',
            new_name='elections_o_person__02dd44_idx',
            old_name='elections_of_person__b6afdf_idx',
        ),
        migrations.RenameIndex(
            model_name='officeholderterm',
            new_name='elections_o_jurisdi_971c18_idx',
            old_name='elections_of_jurisdi_f43331_idx',
        ),
        migrations.RenameIndex(
            model_name='race',
            new_name='elections_r_electio_2b40d8_idx',
            old_name='elections_ra_electio_1a5b8a_idx',
        ),
        migrations.RenameIndex(
            model_name='race',
            new_name='elections_r_office__02f89c_idx',
            old_name='elections_ra_office__eb6597_idx',
        ),
    ]
