# Generated by Django 5.1.6 on 2026-03-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_rename_elections_ca_party_s_8a4d25_idx_elections_c_party_e7727b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidacy',
            name='endorsement_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='is_write_in',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='ranked_choice_voting_round',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='running_mate_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='running_mate_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='race',
            name='about_office',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='race',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='race',
            name='contest_type',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='race',
            name='general_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='has_primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='race',
            name='primary_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='ranked_choice',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='race',
            name='ranked_choice_rank_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='seats_up_for_election',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
